spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF

mycqrs:
  outbox:
    poll-interval: 2000
